quartet_job_que_test:
    resource: "@QuartetJobQueTestBundle/Controller/"
    type:     annotation
    prefix:   /

# BCCResqueBundle
BCCResqueBundle:
    resource: "@BCCResqueBundle/Resources/config/routing.xml"
    prefix:   /resque
